# Generated by Django 4.0.5 on 2022-06-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.TextField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
