# Generated by Django 4.0.5 on 2022-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.TextField(max_length=100)),
                ('activoCategoria', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='activo',
            new_name='activoMarca',
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.TextField(max_length=100),
        ),
    ]
