# Generated by Django 4.0.5 on 2022-06-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigoProducto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
