# Generated by Django 4.0.5 on 2022-06-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_producto_codigoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=10)),
                ('dv', models.TextField(max_length=1)),
                ('nombreUsuario', models.TextField(max_length=50)),
                ('apellidosUsuario', models.TextField(max_length=100)),
                ('fechaNac', models.DateField()),
                ('clave', models.TextField()),
                ('email', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marcaProducto',
            field=models.IntegerField(),
        ),
    ]
