# Generated by Django 4.0.5 on 2022-06-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_usuario_producto_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoPago', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoUsuario', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
