from django.urls import path
from . import views
urlpatterns = [
    path('index', views.indexView, name="index"),
    path('herramientas', views.herramientasView, name="herramientas"),
    path('herrPeque', views.herrPequeView, name="herrPeque"),
    path('herrGrande', views.herrGrandeView, name="herrGrande"),
    path('herrTijera', views.herrTijeraView, name="herrTijera"),
    path('maceteros', views.maceterosView, name="maceteros"),
    path('macRedondo', views.macRedondoView, name="macRedondo"),
    path('macModerno', views.macModernoView, name="macModerno"),
    path('macJardinera', views.macJardineraView, name="macJardinera"),
    path('plantas', views.plantasView, name="plantas"),
    path('plaDolar', views.plaDolarView, name="plaDolar"),
    path('plaLavanda', views.plaLavandaView, name="plaLavanda"),
    path('plaLengua', views.plaLenguaView, name="plaLengua"),
    path('suscripcion', views.susView, name="suscripcion"),
    path('EmpRegister', views.EmpRegisterView, name="EmpRegister"),
    path('EmpLogin', views.EmpLoginView, name="EmpLogin"),
    path('EmpReset', views.EmpResetView, name="EmpReset"),
    path('EmpForget', views.EmpForgetView, name="EmpForget"),
    path('marca', views.viewMarca, name="marca"),
    path('marca/<int:id>/', views.viewReadMarca, name="marca"),
    path('usuario', views.viewUsuario, name="usuario"),
    path('usuario/<int:id>/', views.viewReadUsuario, name="usuario"),
    path('categoria', views.viewCategoria, name="categoria"),
    path('categoria/<int:id>/', views.viewReadCategoria, name="categoria"),
    path('tipoPago', views.viewTipoPago, name = "tipoPago"),
    path('tipoPago/<int:id>/', views.viewReadTipoPago, name="tipoPago"),
    path('tipoUsuario', views.viewTipoUsuario, name="tipoUsuario"),
    path('tipoUsuario/<int:id>/', views.viewReadTipoUsuario, name="tipoUsuario"),
]